// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1qWIJMfGbI1UXuovehXdVDXAbXN5XhKI',
    appId: '1:977055276017:web:22857b800804ae061b4250',
    messagingSenderId: '977055276017',
    projectId: 'my-aggri-app1',
    authDomain: 'my-aggri-app1.firebaseapp.com',
    storageBucket: 'my-aggri-app1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtJSnU1GqQR1W7sMau4pHZPsnSAH-lRuw',
    appId: '1:977055276017:android:a6569197b16fc4991b4250',
    messagingSenderId: '977055276017',
    projectId: 'my-aggri-app1',
    storageBucket: 'my-aggri-app1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1qWIJMfGbI1UXuovehXdVDXAbXN5XhKI',
    appId: '1:977055276017:web:02818b82d4c44ea31b4250',
    messagingSenderId: '977055276017',
    projectId: 'my-aggri-app1',
    authDomain: 'my-aggri-app1.firebaseapp.com',
    storageBucket: 'my-aggri-app1.firebasestorage.app',
  );
}
